services:
  - type: web
    name: gemini-tg-miniapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_MODEL
        value: gemini-3.8-flash
